#!/bin/bash

echo "=========================================="
echo "  DreamHost SMTP Troubleshooting Guide"
echo "=========================================="
echo ""

echo "🔍 Current Configuration:"
echo "- SMTP Server: smtp.dreamhost.com"
echo "- Port: 587"
echo "- Username: hi@astraverify.com"
echo "- Authentication: LOGIN"
echo ""

echo "❌ Error: (535, b'5.7.8 Error: authentication failed: UGFzc3dvcmQ6')"
echo ""

echo "🔧 Possible Solutions:"
echo ""
echo "1. **Check DreamHost Email Settings:**"
echo "   - Log into DreamHost panel"
echo "   - Go to Email > Manage Email"
echo "   - Verify hi@astraverify.com exists and is active"
echo "   - Check if SMTP is enabled for this account"
echo ""

echo "2. **Verify Password:**"
echo "   - Ensure the password is correct"
echo "   - Try resetting the password in DreamHost panel"
echo "   - Make sure there are no special characters causing issues"
echo ""

echo "3. **Alternative SMTP Settings:**"
echo "   Try these alternative configurations:"
echo "   - Server: mail.dreamhost.com (port 587)"
echo "   - Server: smtp.dreamhost.com (port 465 with SSL)"
echo "   - Server: mail.dreamhost.com (port 465 with SSL)"
echo ""

echo "4. **Check DreamHost SMTP Requirements:**"
echo "   - Ensure the email account is not suspended"
echo "   - Check if there are any sending limits"
echo "   - Verify the account has SMTP access enabled"
echo ""

echo "5. **Test with Different Client:**"
echo "   - Try using a different email client to test SMTP"
echo "   - Use Thunderbird, Outlook, or similar to verify credentials"
echo ""

echo "6. **Contact DreamHost Support:**"
echo "   - Ask about SMTP settings for hi@astraverify.com"
echo "   - Verify if there are any restrictions on this account"
echo "   - Check if the account needs special configuration"
echo ""

echo "🚀 Quick Fix Options:"
echo ""
echo "Option A: Switch to Gmail SMTP (Recommended)"
echo "  - More reliable and easier to configure"
echo "  - Better documentation and support"
echo "  - Works well with app passwords"
echo ""

echo "Option B: Try Alternative DreamHost Settings"
echo "  - Test with mail.dreamhost.com"
echo "  - Try port 465 with SSL"
echo "  - Check if different authentication method needed"
echo ""

echo "Option C: Use Different Email Provider"
echo "  - Consider using a different email service"
echo "  - Options: Gmail, Outlook, SendGrid, etc."
echo ""

echo "Would you like me to:"
echo "1. Update the configuration to use Gmail SMTP?"
echo "2. Try alternative DreamHost SMTP settings?"
echo "3. Help you contact DreamHost support?"
echo "4. Test with a different email provider?"
