// Version utility for AstraVerify frontend
// This file is auto-generated by the build process

export const VERSION = '2025.08.15.01-Beta';
export const BUILD_DATE = '2025-08-15';
export const COPYRIGHT = '© AstraVerify.com - a CloudGofer.com service';

// Function to get full version info
export const getVersionInfo = () => {
    return {
        version: VERSION,
        buildDate: BUILD_DATE,
        copyright: COPYRIGHT
    };
};

// Function to get formatted footer text
export const getFooterText = () => {
    return `v${VERSION} | ${COPYRIGHT}`;
};
